## USER SETTINGS:

# Provide download paths. Default is /downloads
save_dir:
  series: "downloads"
  movies: "downloads"

# Temp folder. This is where downloading files are temporarly
# stored while being processed. It might be a good idea to have this
# on the same hdd as your download folder. Default is /temp
temp_dir: "temp"

# Specify file format. Default: mkv
format: mkv

# Specify muxer (ffmpeg or mkvmerge) Default: mkvmerge
muxer: mkvmerge

# Customize filename output for series and movies
# Default file names follow the current P2P standard: Title.S01E01.EpisodeName.1080p.SERVICE.WEB-DL.AUDIO.CODEC
# NOTE: {year} is dependent on if the service API has it configured, which is hit or miss
# Manually adding the year for each series is recommended if you need it included
filename: 
  series: "{title}.S{season}E{episode}.{name}.{resolution}.{service}.WEB-DL.{audio}.H.264"
  movies: "{title}.{year}.{resolution}.{service}.WEB-DL.{audio}.H.264"

# Thread-count. Set how many concurrent fragments N_m3u8DL-RE should download
# More threads can speed up slow downloads, but too many could potentially
# leave a bigger footprint? Experiment with it.
threads: "16"

# Set TV series to be sorted into respective season folders (true or false)
seasons: "true"

## VIDEO/AUDIO/SUBTITLES:

# These settings are configured per service in /services/config