## Copy this config file to a service folder to set service-specific settings

# Provide download paths. Default is /downloads
save_dir:
  series: "downloads"
  movies: "downloads"

# Temp folder. This is where downloading files are temporarly
# stored while being processed. It might be a good idea to have this
# on the same hdd as your download folder. Default is /temp
temp_dir: "temp"

# Specify file format. Default: mkv
format: mkv

# Specify muxer (ffmpeg or mkvmerge) Default: mkvmerge
muxer: mkvmerge

# Use shaka-packager instead of mp4decrypt to decrypt (true or false)
shakaPackager: "false"

# Customize filename output for series and movies
# Default file names follow the current P2P standard: Title.S01E01.EpisodeName.1080p.SERVICE.WEB-DL.AUDIO.CODEC
# NOTE: {year} is dependent on if the service API has it configured, which is hit or miss
# Manually adding the year for each series is recommended if you need it included
filename: 
  series: "{title}.S{season}E{episode}.{name}.{resolution}.{service}.WEB-DL.{audio}.H.264"
  movies: "{title}.{year}.{resolution}.{service}.WEB-DL.{audio}.H.264"

# Thread-count. Set how many concurrent fragments N_m3u8DL-RE should download
# More threads can speed up slow downloads, but too many could potentially
# leave a bigger footprint? Experiment with it.
threads: "16"

# Set TV series to be sorted into respective season folders (true or false)
seasons: "true"

# Set video options. See "N_m3u8DL-RE --morehelp select-video" for guidance. Default: best
video:
  select: "for=best"
  drop:

# Set audio options. See "N_m3u8DL-RE --morehelp select-audio" for guidance. Default: best
audio:
  select: "for=best"
  drop:

# Set subtitle options. See "N_m3u8DL-RE --morehelp select-subtitle" for guidance. Default: all
subtitles:
  select: "all"
  drop:
  no_mux: "false" # If "true", subtitles will be stored separately
  fix: "true" # Clean and convert subtitles. If "false", subtitles remain untouched