## SERVICE SETTINGS:

my5:
  keys:
    hmac: "keec4EdbQjn5M3WBQZH07Q=="
    aes: "GEpQMh9S+hayOzWxRaXeuQ=="
  api:
    base: "https://corona.channel5.com"
    content: "https://corona.channel5.com/shows/{show}/episodes.json?platform=my5desktop&friendly=1&linear=true"
    vod: "https://cassie.channel5.com/api/v2/media/my5desktopng/{id}.json?timestamp={timestamp}"
    
all4:
  key: "QVlESUQ4U0RGQlA0TThESA=="
  iv: "MURDRDAzODNES0RGU0w4Mg=="
  vod: "https://ais.channel4.com/asset/{asset_id}?client=android-mod"

ctv:
  api: "https://api.ctv.ca/space-graphql/graphql"
  lic: "https://license.9c9media.ca/widevine"

stv:
  vod: "https://player.api.stv.tv/v1/episodes?"
  api: "https://edge.api.brightcove.com/playback/v1/accounts"

uktv:
  vod: "https://vschedules.uktv.co.uk/vod/"
  api: "https://edge.api.brightcove.com/playback/v1/accounts/"

crkl:
  api: "https://prod-api.crackle.com"
  x-key: "5FE67CCA-069A-42C6-A20F-4B47A8054D46"

roku:
  api: "https://therokuchannel.roku.com/api/v2/homescreen/content/https%3A%2F%2Fcontent.sr.roku.com%2Fcontent%2Fv1%2Froku-trc%2F"
  vod: "https://therokuchannel.roku.com/api/v3/playback"

pluto:
  api: "https://service-vod.clusters.pluto.tv/v4/vod"
  lic: "https://service-concierge.clusters.pluto.tv/v1/wv/alt"