## SERVICE SETTINGS FOR CHANNEL5

base: "https://corona.channel5.com"
content: "https://corona.channel5.com/shows/{show}/episodes.json?platform=my5desktop&friendly=1&linear=true"
single: "https://corona.channel5.com/shows/{show}/seasons/{season}/episodes/{episode}.json?platform=my5desktop&friendly=1"
vod: "https://cassie.channel5.com/api/v2/media/my5desktopng/{id}.json?timestamp={timestamp}"
gist: "https://gist.githubusercontent.com/stabbedbybrick/d775a9ce07196df0e3b9ea827fb4f5f7/raw/s.txt?={timestamp}"



## SERVICE SETTINGS

# Changes made here will override the global config

# Set video options. See "N_m3u8DL-RE --morehelp select-video" for guidance. Default: best
# Using --quality will override this quality setting
video:
  track: "for=best"
  drop:

# Set audio options. See "N_m3u8DL-RE --morehelp select-audio" for guidance. Default: best
audio:
  track: "for=best"
  drop:

# Set subtitle options
subtitles:
  no_mux: "false" # If "true", subtitles will be stored separately
  clean: "true" # Clean and convert subtitles. If "false", subtitles remain untouched