## SERVICE SETTINGS FOR TUBI TV

content: "https://tubitv.com/oz/videos/{content_id}/content?video_resources=hlsv6_widevine_nonclearlead&video_resources=hlsv6"


## SERVICE SETTINGS

# Changes made here will override the global config

# Set video options. See "N_m3u8DL-RE --morehelp select-video" for guidance. Default: best
# Using --quality will override this quality setting
video:
  track: "for=best"
  drop:

# Set audio options. See "N_m3u8DL-RE --morehelp select-audio" for guidance. Default: best
audio:
  track: "for=best"
  drop:

# Set subtitle options
subtitles:
  no_mux: "false" # If "true", subtitles will be stored separately
  clean: "true" # Clean and convert subtitles. If "false", subtitles remain untouched