## SERVICE SETTINGS FOR UKTV PLAY

vod: "https://vschedules.uktv.co.uk/vod/"
api: "https://edge.api.brightcove.com/playback/v1/accounts/"


## SERVICE SETTINGS

# Changes made here will override the global config

# Set video options. See "N_m3u8DL-RE --morehelp select-video" for guidance. Default: best
# Using --quality will override this quality setting
video:
  track: "for=best"
  drop:

# Set audio options. See "N_m3u8DL-RE --morehelp select-audio" for guidance. Default: best
audio:
  track: "for=best"
  drop:

# Set subtitle options
subtitles:
  no_mux: "false" # If "true", subtitles will be stored separately
  clean: "true" # Clean and convert subtitles. If "false", subtitles remain untouched